### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by rob42** [SignalK/playground#2]
This is possibly more a specification issue than a playground issue, but putting here for a start anyway
`source` doesnt allow primitive, so a ref to actual source doesnt work
`source` wants `label` so same problem
`vessel.motu` is not valid, it wants a valid mmsi, but unique text name should be allowed
`timestamp` is ignored at least, maybe causing an error too.

**Comment by tkurki** [comment]
Closing here, as these are really specification issues.
